
aws:
    sqs:
        accessKey:
        secretKey:
        region:
        endpoint:
        queueName:
        sessionSize:

ibm:
    mq:
        accessKey:
        secretKey: 
        region: 
        endpoint: 
        queueName: 
        sessionSize: 